services:
  clickhouse:
    image: yandex/clickhouse-server
    container_name: "clickhouse"
    platform: linux/amd64
    ports:
      - 8123:8123
      - 9000:9000

  ch-migrate:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: "ch_migrate"
    volumes:
      - .:/src
      - ./migrations:/src/migrations
      - ./Makefile:/src/Makefile
    tty: true
    depends_on:
      - clickhouse
